name: Update and Deploy HTML to Pages

on:
  schedule:
    - cron: '0 0-15/1,20,23 * * *'
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      changes: ${{ steps.check_changes.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python script
        env:
          ZZU_CONFIG: ${{ secrets.ZZU_CONFIG }}
          ZZU_NOTIFIER: ${{ secrets.ZZU_NOTIFIER }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          python3 ./index.py
          python3 ./markdown.py >> $GITHUB_STEP_SUMMARY
        
      - name: Check for changes
        id: check_changes
        run: echo "changes=$(git diff --shortstat HEAD)" >> $GITHUB_OUTPUT

      - name: Get last commit message
        id: commit_message
        run: echo "last_commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: ${{ steps.check_changes.outputs.changes != '' && !startsWith(steps.commit_message.outputs.last_commit_message, 'Updated at ') }}
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git add .
          git commit -m "Updated at $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push
          
      - name: Force push changes
        if: ${{ steps.check_changes.outputs.changes != '' && startsWith(steps.commit_message.outputs.last_commit_message, 'Updated at ') }}
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git reset --soft HEAD^
          git add .
          git commit -m "Updated at $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push --force
      
      - name: Setup Pages
        if: ${{ steps.check_changes.outputs.changes != '' }}
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: ${{ steps.check_changes.outputs.changes != '' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: './page'

  deploy:
    needs: build
    if: ${{ needs.build.outputs.changes != '' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
