name: Fetch Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,8,16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get current UTC time
        run: echo "timestamp=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
        id: time

      - name: Fetch Data
        env:
          ZZU_CONFIG: ${{ secrets.ZZU_CONFIG }}
          ZZU_NOTIFIER: ${{ secrets.ZZU_NOTIFIER }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

        run: |
          python3 ./index.py
          
      - name: Push if there are any changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git status
          git add .
          git commit -m '${{ steps.time.outputs.timestamp }} UTC' && git push || echo "No changes to commit"
