name: Test Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch Data
        env:
          ZZU_CONFIG: ${{ secrets.ZZU_CONFIG }}
          ZZU_NOTIFIER: ${{ secrets.ZZU_NOTIFIER }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: python3 ./index.py

      - name: Check for changes
        id: check_changes
        run: echo "changes=$(git diff --shortstat HEAD)" >> $GITHUB_OUTPUT
        
      - name: Push changes
        if: ${{ steps.check_changes.outputs.changes != '' }}
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git status
          git add .
          git commit -m "Updated at $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          git push
